# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BlogNet
email: tom.vandenberg@infosupport.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogging site
twitter_username: TomB_171296
github_username: tom172196
minimal_mistakes_skin: default
search: true

url: "https://blognet.tech"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Tom van den Berg"
  avatar : "/assets/images/profile.jpg"
  bio    : "I'm a software engineer at Info Support in the Netherlands. 
  I write blogs about software development, architecture and other cool stuff."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/tom-van-den-berg-953643127/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TomB_171296"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tom171296"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/TomB_171296"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tom171296"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
